#!/usr/bin/env bash
# Configuring_HAProxy load_balancer

# update_the_package_list 
sudo apt-get -y update

# install_required_packages
sudo apt-get -y install software-properties-common

# Add_the_HAProxy repository_and install_HAProxy 2.0
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

# HAProxy_configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend_webservers
    balance roundrobin
    server 266951-web-01 18.207.141.252:80 check
    server 266951-web-02 54.236.16.254:80 check
"
# Add_your_HAProxy_configuration_to_haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Start_the_HAProxy_service
sudo service haproxy start
